# A sample configuration file for generating Dockerfiles. You may find configuration files under folder images/config/.

# Base name of the configuration file must be of a specific version of image openswoole/swoole, e.g.,
#   * 4.3.6
#   * 4.4.6

# Options for field "status": "under development", "released", "end-of-life".
#   * "under development":
#     Under development and is actively maintained. This status is also used in GitLab Actions to identify most-recent stable releases.
#   * "released":
#     The tag is frozen and won't be updated any more.
#   * "end-of-life":
#     The tag is not actively maintained and is not suggested to be used any more.
status: "under development"
php: # List of PHP versions to build for.
  - "7.2.19"
  - "7.3.6"
image:
  composer:
    version: "1.8.6" # Composer version.
  inotify: false # Install package inotify-tools or not for non-Alpine images. By default it's not installed.
  php_extensions: # List of PECL extensions to be installed for non-Alpine images.
    zip: # An extension name.
      version: "1.15.4" # Optional.
      enabled: true # Enable the extension or not. By default it's disabled.
