# The YAML configuration file for generating Dockerfile of image openswoole/swoole:4.8.1.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - "8.1.11"
  - "8.2.0"
  - "8.3.0"
image:
  composer:
    version: "2.6.6"