# The YAML configuration file for generating Dockerfile of image openswoole/swoole.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - "7.4"
  - "8.0"
  - "8.1"
  - "8.2"
image:
  composer:
    version: "2.1.6"
  inotify: true
